version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: rabbitmq-telegram
    container_name: rabbitmq-telegram
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  bot_db:
    image: postgres
    container_name: bot_db
    environment:
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bot
    ports:
      - "5555:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d coin" ]
      interval: 8s
      timeout: 4s
      retries: 4


volumes:
  rabbitmq_data:
