server:
  port: 8086
logging:
  file:
    name: node/logs/node.log
  level:
    com.mergeteam: debug
spring:
  rabbitmq:
    username: admin
    password: coincontrol
    host: localhost
    port: 5672
  datasource:
    driver-class-name: org.postgresql.Driver
    username: bot
    password: password
    url: jdbc:postgresql://localhost:5555/bot
  jpa:
    generate-ddl: true
telegram:
  bot:
    token: 7199810010:AAFZ6eDp-g7IeuDNtTAPgnMaHXjMc_EbkWg
  service:
    file_info.uri: https://api.telegram.org/bot{token}/getFile?file_id={fileId}
    file_storage.uri: https://api.telegram.org/file/bot{token}/{filePath}
    mail.uri: http://127.0.0.1:8099/mail/send
link:
  address: 127.0.0.1:8090
crypto:
  salt: salt12AQd2DQjifsEr34fs